export const CROSSFADE_DURATION_DEFAULT_SEC = 2;
export const CROSSFADE_DURATION_MIN_SEC = 1;
export const CROSSFADE_DURATION_MAX_SEC = 8;
export const POSITION_SAVE_INTERVAL_MS = 2000;
export const MIN_POSITION_TO_SAVE_SEC = 3;
export const POSITION_SAVE_END_THRESHOLD = 0.95;
export const FULL_BUFFER_TOLERANCE_SEC = 0.25;
